title: Ari Gianatiempo 🤓
description: > # this means to ignore newlines until "baseurl:"
  Extracts from useful and interesting articles I read around with personal 
  notes and comments to consolidate my understanding on the subject and keep 
  record of it to check when needed.
permalink: ":title/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ariel Gianatiempo # add your name
author-img: ariel.jpeg # add your photo
about-author: I am a front-end developer focused on React. # add description
social-github: gianatiempo # add your Github handle
social-linkedin: gianatiempo # add your Linkedin handle

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
